apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: chat2
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: chat2
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: REDIS_PASSWORD
      value: "chat212345"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.5"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: chat2
data:
  redis-config: |
    requirepass chat212345
    maxmemory 1gb
    maxmemory-policy allkeys-lru
    appendonly yes
